### ISSUE TITLE
Develop Visual Allocation Comparisons

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/electricity-demand-mapping#7]
We need some way to understand how different demand allocations compare to each other, and how that varies across both time and space.

# Correlation and regression for selected regions
* Within a particular output BA, shows the overall correlation between two demand allocations
* No temporal element, but gives an overall picture within each BA of how well the two allocations correlate.
* Can look at how different output geometries change the correlations between different allocations.
* Would expect better correlations with bigger areas.
* Can explore how (e.g.) high demand regions correlate, vs. low demand regions -- important for overall metric of similarity.
* Sum of mean squared errors would help focus on large-demand areas.
* Using deltas between different allocations to scale one or the other doesn't really make sense since there's no ground truth.
![image](https://user-images.githubusercontent.com/596279/89229815-c59ee100-d5a7-11ea-8cb4-06c2b68613da.png)

# Periodic error profiles
* E.g. hour-of-day, day-of-week, month-of-year
* Can be done for any output area (BA, state, country, etc.)
* Allow comparisons for how the differences are different in different regions, or if there's a universal pattern of difference.
* Can use several different metrics of error / difference
* Mean Squared Error (MSE), R^2, mean absolute percentage error (MAPE?)
* Don't worry about the NA counts yet -- need to fix those within the timeseries. Maybe do one column of abolute errors, and another of relative errors.
![image](https://user-images.githubusercontent.com/596279/89229793-b750c500-d5a7-11ea-9936-257f42f34a6b.png)

# Regional demand profiles
* Shows periodic demand profiles for different regions
* Can compare multiple allocations with each other
* Statistical envelope shows how much variation there is in each profile
* Gap between allocations would correspond to the bar charts in the above.
* Need units on the y-axes (MW?)
![image](https://user-images.githubusercontent.com/596279/89229767-ad2ec680-d5a7-11ea-860e-84e4ce93998d.png)

# Demand area coverage
* Shows what portion of each output BA is covered by at least one input demand region.
* A similar but different area map would show multiplicity of coverage -- how many times is a given region covered?
* Should it be output in terms of the aggregated output areas? Or on a county-by-county basis?
![image](https://user-images.githubusercontent.com/596279/89229726-98eac980-d5a7-11ea-92fb-3819143b2803.png)

# 24 x 365 heat map
* Shows error metrics as a function of hour-of-year
* Allows simultaneous visualization of diurnal, weekly, and seasonal patterns
* Axis labels: Day of Year / Hour of Day
* Needs to be labeled for location (where is this?)
* Why are there individual days that look awful?
![image](https://user-images.githubusercontent.com/596279/89229743-a4d68b80-d5a7-11ea-9ac8-eb58137cfe48.png)

**Comment by zaneselvans** [comment]
## Next steps
* Choose several diverse NREL BAs to look at, make sure they have substantial demand / population in them.
  * Desert Southwest
  * Pacific Northwest
  * Deep Southeast
  * Midwest
  * Northeast
* Make heat maps for each of those regions so we can see how the patterns change with location.
* Make regional demand profiles for each of those regions
* Make periodic error profiles (both absolute and relative) for each of those regions
* Make correlation / regression plots for each of those as well.

**Comment by zaneselvans** [comment]
Hey @yashkumar1803, on the heatmap plot, what is the geographic area being covered, and how? This is all 8760 hours for a year, so if it's just two areas being compared to each other (i.e. two individual hourly time series for one year) then what does R^2 mean? There would only be a single point at each hour in each time series?  Or is this looking at the correlation between all of the data points for a given hour-of-year in the NREL data (across all the REEDS BAs) and all of the data points for a given hour-of-year for our allocation?

**Comment by yashkumar1803** [comment]
@zaneselvans, you are right. Maybe, R2 may not be the best metric for a heatmap. R2 over here means what you mentioned at the end i.e. correlation between all of the data points for a given hour-of-year in the NREL data (across all the REEDS BAs) and all of the data points for a given hour-of-year for our allocation. It was just an example metric.

**Comment by yashkumar1803** [comment]
# Changes Required

## Correlation and Regression
1. Plot all regions if select_regions is `None` separately, or plot them on the same axis (check)
2. Better labels instead of `alloc` and actual (check)
3. Adjust `suptitle`. Right now, the top adjustment is set at 0.95. It needs to be dynamic based on plotting heuristics. Can be improved using `tight_layout` (still needs fixing. curve fitting required to adjust suptitle)
4. Add units on the labels. (check)

## Periodic error profiles:
1. Remove `NA` figures columns (check)
3. Add units on the labels (check)
4. Add a `select_regions` argument to analyze the error for a region subset (check)

## Regional demand profile
1. Units on the Y-axis (check)
2. If `select_region` is None, plot demand profile for the whole of US or plot separate charts for all regions (check)

## Demand area coverage
1. Different colors for demand completely absent (check)
2. Gradient scale for the number of times an area is covered (check)
3. Only allocated and disaggregated geometries to be used for demand to show maximum information (check)

## 24 X 365 Heat Map
1. Unit spacing improve (probably label at every 7 days)
2. Add axis labels
3. Add `select_region` option in the label to plot for a subset of the regions

**Comment by yashkumar1803** [comment]
Completed changes in the error visualization functions
